# Generated by Django 4.2.11 on 2024-04-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-username', 'mob', 'password']},
        ),
    ]
