# Generated by Django 4.2.11 on 2024-04-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
